<a href="https://colab.research.google.com/github/NataliaPietrzak123/BootcampDataScience/blob/main/01_numPy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PODSTAWY NUMPY

In [ ]:
import numpy as np
np.__version__

'1.22.4'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [ ]:
x = np.array([1,3])
x

In [ ]:
print(x)

In [ ]:
type(x)

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 1.4])
print(x)
x.dtype

In [ ]:
x = np.array([[1,2], [-3, 1]])
x

In [ ]:
x.ndim

2

In [ ]:
x.shape

In [ ]:
x = np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


macierz 3D

In [ ]:
x = np.array(
    [[[ 2,4,6],
    [3,6,7]],
    [[7,4,2],
     [3,6,9]]]
)


Typy Danych

In [ ]:
A = np.array([1,2,3],
             dtype = 'float')
A.dtype

dtype('float64')

In [ ]:
A = np.array([1.0,2.3,3.3],
             dtype = 'float')
A.dtype

dtype('float64')

In [ ]:
A 

array([1. , 2.3, 3.3])

Tworzenie Tablic

In [ ]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Podstawowe operacje na tablicach

In [ ]:
A= np.array([3,1,4,2])
B= np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A+B
A - B
A * B
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A+3
A-3
A*2
A+3*B

array([12, -2, 13,  8])

In [ ]:
np.add(A,B)
np.subtract(A,B)
np.multiply(A,B)
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
X = np.array([[1,3], [-2,0]])
Y = np.array([[6,0],[-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
X*Y

array([[6, 0],
       [2, 0]])

In [ ]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y)
X @Y

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolosowych

In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn(10, 4)

array([[ 0.14404357,  1.45427351,  0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433,  1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574, -2.55298982,  0.6536186 ],
       [ 0.8644362 , -0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  1.20237985],
       [-0.38732682, -0.30230275, -1.04855297, -1.42001794],
       [-1.70627019,  1.9507754 , -0.50965218, -0.4380743 ],
       [-1.25279536,  0.77749036, -1.61389785, -0.21274028]])

In [ ]:
np.random.randint(10)

7

In [ ]:
np.random.randint(low=10, high=101)

89

In [ ]:
A = np.random.randint(low=10, high=101, size = 10)

In [ ]:
np.random.choice([4,2,1,3,5])

In [ ]:
np.random.choice(['python', 'java', 'sql'])

Podstawiwe funckje

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.sqrt(9)

3.0

In [ ]:
np.all([2,3,1])

True

In [ ]:
np.any([0,0,0])

False

In [ ]:
bool(1.3)

True

In [ ]:
A = np.random.rand(5)
A

array([0.97958673, 0.35944446, 0.48089353, 0.68866118, 0.88047589])

In [ ]:
np.argmax(A)

0

In [ ]:
A[np.argmax(A)]

0.9795867288127285

Indeksowanie, wycinanie

In [ ]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
#A[idx], A[start,stop], A[:stop], A[start:]

A[2]
A[[0,2]]
A[-1]

19

In [ ]:
A[10:15]


In [ ]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[:,-1]

array([ 4,  9, 14, 19])

In [ ]:
A[1,3]

8

In [ ]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
A[1,2] = 14  # zmiana wartości w tablicy
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracja po tablicach

In [ ]:
for row in A:
  print(row[0])

0
5
10
15


In [ ]:
for item in A.flat:
  print(item)

Zmiana rozmiaru tablic

In [ ]:
A.shape

(4, 5)

In [ ]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
A.ravel()       #metoda wypłaszaczająco dane (na jednowymiarowe)

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
A.T #Transpozycja

Maski logiczne

In [ ]:
A = np.arange(start=-10, stop=10, step = 0.5)
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [ ]:
A>10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
A[A>5]

array([5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.bitwise_and(A>-5,A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
A[np.bitwise_and(A>-5,A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [ ]:
np.bitwise_or(A<-5, A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
git push -u origin main

SyntaxError: ignored