<a href="https://colab.research.google.com/github/NataliaPietrzak123/BootcampDataScience/blob/main/Wprowadzenie/Algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
v1 = np.array([0,4])
v1

array([0, 4])

In [5]:
np.linalg.norm(v1)

4.0

In [6]:
v2 = np.array([-10,10,13])
np.linalg.norm(v2)

19.209372712298546

Odległość dwóch punktów na płaszczyźnie

In [8]:
p = np.array([3,0])
q = np.array([0,4])

np.linalg.norm(p-q)

5.0

In [9]:
p = np.array([3,0,1])
q = np.array([0,4,2])
np.linalg.norm(p-q)

5.0990195135927845

Mnożenie macierzy

In [13]:
p = np.array([[3,0], [8,2]])
q = np.array([0,4])

Z= np.dot(p,q)
Z

array([0, 8])

Wyznacznik Macierzy

In [18]:
p = np.array([[3,0], [8,2]])
np.linalg.det(p)


6.0

Ślad macierzy

In [17]:
p = np.array([[3,0], [8,2]])
p
np.trace(p)

5

In [19]:
np.eye(5, dtype='int')   #macierz jednostkowa

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [21]:
   #macierz odwrotna
p = np.array([[3,0], [8,2]])
B = np.linalg.inv(p)
B

array([[ 0.33333333,  0.        ],
       [-1.33333333,  0.5       ]])

In [23]:
#Macierz transponowana
np.transpose(p)
p.T

array([[3, 8],
       [0, 2]])

Rozwiązywanie układów równań

In [25]:
A = np.array([[2,4],[1,-1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [27]:
B = np.array([[10],[-1]])
B

array([[10],
       [-1]])

In [28]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv,B)
X

array([[1.],
       [2.]])

In [29]:
X.shape

(2, 1)